# Generated by Django 4.1.3 on 2024-04-23 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DevFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsc', models.TextField(verbose_name='Описание')),
                ('file', models.FileField(upload_to='dev_file/file/%Y/%m/%d/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Наработанные файл',
                'verbose_name_plural': 'Наработанные файлы',
            },
        ),
        migrations.CreateModel(
            name='LastFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_start', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to='dev_file/file/%Y/%m/%d/', verbose_name='Файл')),
                ('comment_self', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('comment_user', models.TextField(blank=True, null=True, verbose_name='Комментарий заказчика')),
            ],
            options={
                'verbose_name': 'Последняя редакция',
                'verbose_name_plural': 'Последние редакции',
            },
        ),
        migrations.CreateModel(
            name='PaymentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(verbose_name='Оплата')),
                ('data_start', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='ScientificSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Научный руководитель',
                'verbose_name_plural': 'Научные руководители',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Имя')),
                ('link', models.CharField(max_length=155, verbose_name='Соц. сеть')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=155, verbose_name='Тема диплома')),
                ('price', models.IntegerField(verbose_name='Цена диплома')),
                ('is_technical_part', models.BooleanField(verbose_name='Разработан сайт')),
                ('is_design', models.BooleanField(verbose_name='Разработан дизайн')),
                ('link_site', models.CharField(max_length=255, verbose_name='Ссылка на сайт')),
                ('link_figma', models.CharField(max_length=255, verbose_name='Ссылка на фигму')),
                ('developments', models.ManyToManyField(blank=True, null=True, to='server.devfile', verbose_name='Наработанные данные')),
                ('last_file', models.ManyToManyField(blank=True, null=True, to='server.lastfile', verbose_name='Последняя редакция')),
                ('paid', models.ManyToManyField(blank=True, null=True, to='server.paymentuser', verbose_name='Оплата')),
                ('scientific_supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.scientificsupervisor', verbose_name='Научный руководитель')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.userprofile', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявка',
            },
        ),
    ]
